apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-service-mesh-linkerd-ingress
  namespace: kube-service-mesh-linkerd
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/subnets: ""
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: kube-service-mesh-main-service
                port:
                  number: 3000
