---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-service-mesh-service-1
  namespace: kube-service-mesh-linkerd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-service-mesh-service-1-deployment
  namespace: kube-service-mesh-linkerd
  labels:
    app: kube-service-mesh-service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-service-mesh-service-1
  template:
    metadata:
      labels:
        app: kube-service-mesh-service-1
    spec:
      serviceAccountName: kube-service-mesh-service-1
      containers:
        - name: kube-service-mesh-service-1
          image: narayananramu/kube-service-mesh-service-1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
